[workspace]
members = ["yang-codegen", "yang-gnmi", "yang-parser"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Terje Lafton terje@lafton.io"]
edition = "2021"
license = "MIT"
repository = "https://github.com/TerjeLafton/yang-rs"
