[package]
name = "yang-parser"
description = "Parser for YANG files that outputs Rust structs"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pest = "2.8"
pest_derive = "2.8"
thiserror = "2.0.12"
