[package]
name = "yang-gnmi"
description = "gNMI utility that lets you interact with network devices using YANG modules."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
